### ISSUE TITLE
清除缓存过后，页面刷新打不开，疑是把登录信息清空了，并且作品变多了

### ISSUE THREAD

**Issue by yi1834257499** [h5ds/h5ds-bugs#1]
## 环境信息
![image](https://user-images.githubusercontent.com/28852233/44373928-55b00100-a51e-11e8-8198-cf085d22e841.png)

- 错误地址：
- 浏览器以及版本： 
google浏览器，最新版

## 问题描述
创建作品-》编辑-》保存-》清除缓存-》
![image](https://user-images.githubusercontent.com/28852233/44374013-c0613c80-a51e-11e8-8bbb-5fb697f47dcc.png)
-》打开首页-》需登录-》登录后作品变多了
创建作品-》点击
![image](https://user-images.githubusercontent.com/28852233/44374149-6d3bb980-a51f-11e8-895f-da53a01d8e16.png)

##网址
http://www.h5ds.com

**Comment by mtsee** [comment]
thanks! 正在处理...

**Comment by hstarorg** [comment]
@mtsee 建议解决后，也回复一下问题原因，以及解决方案。

**Comment by mtsee** [comment]
core/components/header/header.jsx 修改代码即可
```
// 清除缓存
    clears = () => {
        clearStorage('APP_DATA');
        clearStorage('APP_EDATA');
        clearStorage('APP_STORE');
        deleteDB('H5DS');
        window.location.reload();
    };
```
