### ISSUE TITLE
登录密码提示bug

### ISSUE THREAD

**Issue by the-old-time** [h5ds/h5ds-bugs#4]
## 环境信息

- 错误地址：
- 浏览器以及版本： 

## 问题描述

![image](https://user-images.githubusercontent.com/33015395/45341957-087bf800-b5cf-11e8-843d-74fd8861bfb9.png)

**Comment by mtsee** [comment]
无法重现你那个BUG呢、请问下操作流程是？

**Comment by the-old-time** [comment]
注册的时候 不输入密码提示请输入手机号 。。。 不知是你们这样设置的还是疏忽的原因

**Comment by mtsee** [comment]
嗯，是个BUG。我这边修改下
